### ISSUE TITLE
Exception in pool task: Unable to open stream for ".../.laz" with error 'No such file or directory'

### ISSUE THREAD

**Issue by ToHold** [connormanning/entwine#104]
Hello everybody,
I need your help because when i try to index my laz file with entwine, i got this error : 

```
Scanning input
1 / 1: /home/theo-geomapping/Documents/pointcloud/pointcloud.laz
Exception in pool task: Unable to open stream for '/home/theo-geomapping/Documents/pointcloud/pointcloud.laz' with error 'No such file or directory'
Correcting malformed Bounds
Maximal extents: [(-2147483648, -2147483648, -2147483648), (2147483647, 2147483647, 2147483647)]
Scaled bounds:   [(-9223372036854775808, -9223372036854775808, -9223372036854775808), (-9223372036854775808, -9223372036854775808, -9223372036854775808)]
Encountered an error: Bounds are too large for the selected scale
Exiting.
```
The command used is : 

`sudo docker run -it -v $HOME:/opt/data connormanning/entwine     build -i "/home/theo-geomapping/Documents/pointcloud/pointcloud.laz" -o "/home/theo-geomapping/Documents/pointcloud/"`

Can you tell me how can I index my file ? Where is my error ?
Thanks

**Comment by connormanning** [comment]
Looks like a docker volume mapping issue.  `/home` does not look like it's mapped into the docker container so I don't understand the path mappings here.  If I had to guess, you want your mapping as something like `docker run -it -v ~$HOME:/home` instead of mapping it to `/opt/data`, which you aren't using.  See https://docs.docker.com/engine/reference/commandline/run/#mount-volume--v---read-only.
