### ISSUE TITLE
ticks value appears to be ignored in JSON config file

### ISSUE THREAD

**Issue by adamsteer** [connormanning/entwine#116]
I’m experimenting with different config options to try and write out smaller chunks of EPT to do some performance testing. Assuming `ticks` is the appropriate parameter to change, if I specify a value on the command line:

`entwine build config.json -i infiles/* -o /outputlocation —ticks 128`

…I get build parameters as follows:

```
Build parameters:
	Ticks: 128
	Resolution 2D: 128 * 128 = 16,384
	Resolution 3D: 128 * 128 * 128 = 2,097,152
	Overflow threshold: 8,192
```
However, if I specify ticks in the JSON config only, it appears to be ignored (for any value, not just smaller than default). Using a config.json like:

```
{
    "dataType": "laszip",
    "hierarchyType": "json",
    "threads": 6,
    "ticks": 128
}
```
..and running:

`entwine build config.json -i infiles/* -o /outputlocation`

results in the default tick values being applied:

```
Build parameters:
	Ticks: 256
	Resolution 2D: 256 * 256 = 65,536
	Resolution 3D: 256 * 256 * 256 = 16,777,216
	Overflow threshold: 32,768
```

…using dockerised entwine (connormanning/entwine latest). I hope my JSON is wrong, or it’s an otherwise simple fix.

**Comment by connormanning** [comment]
I believe that your second invocation is treating `config.json` as an input point cloud file - rather than a configuration.  Rather than the configuration file being specified as the first argument to `entwine build` as specified in the `1.x` releases, the current code should use the `-c` or `--config` flag to specify a configuration file.

You should be able to confirm this by looking at the very first few lines of output from your command - I believe you'll see your config file displayed in the pre-scan portion, where it will be ignored since it's not a point cloud file.

**Comment by connormanning** [comment]
It might be a good idea to remove the default option to `entwine build` from being treated as input files.  Currently this choice allows the syntax: `entwine build data.laz -o ~/output` - but requiring the `-i` flag for inputs might improve clarity, especially in this case where the behavior has changed since previous versions.  If this were the case, you'd have gotten an error in your second invocation.

**Comment by adamsteer** [comment]
OK, this works as expected:

`entwine build -c config.json -i infiles/* -o /outputlocation`

thanks!

+1 for requiring `-i input/files/*` from me.
