### ISSUE TITLE
Cesium point cloud density -  geometricErrorDivisor & scale.

### ISSUE THREAD

**Issue by devdylan** [connormanning/entwine#117]
Using latest docker image of entwine, I am noticing the output Cesium model is considerably less dense than the input las file, as viewed in ccViewer.

Looking at the documentation, it appears that [`geometricErrorDivisor`](https://github.com/connormanning/entwine/blob/master/doc/configuration.md#geometricerrordivisor) may offer a solution; however, I am not able to set this variable via a configuration file OR directly as an argument (both should be possible according to the documentation). When I run `convert`, I get `Root geometric error: 66.5`.

Is geometricErrorDivisor the reason my point cloud is not as dense?

Regarding not being able to set geometricErrorDivisor:

As a direct argument:
```
docker run -it \
    -v $PWD/../../..:/data \
    connormanning/entwine convert \
        -i /data/output/entwine/ecef \
        --threads 8 \
        --colorType 'rgb' \
        -o /data/output/entwine/cesium \
        --geometricErrorDivisor 16.0 

> Entwine: Converting Entwine Point Cloud to Cesium 3D Tiles...
Encountered an error: Error handling argument '--geometricErrorDivisor' with value "16.0": Value is not convertible to double.
Exiting.
```

Via a config file:
```
docker run -it \
    -v $PWD/../../..:/data \
    connormanning/entwine convert \
        -i /data/output/entwine/ecef \
        --threads 8 \
        --colorType 'rgb' \
        -o /data/output/entwine/cesium \
        --config /data/scripts/entwine/convert/config.json 

> Entwine: Converting Entwine Point Cloud to Cesium 3D Tiles...
Encountered an error: Error handling argument '--geometricErrorDivisor' with value "16.0": Value is not convertible to double.
Exiting.

docker run -it \
    -v $PWD/../../..:/data \
    connormanning/entwine convert \
        -i /data/output/entwine/ecef \
        --threads 8 \
        --colorType 'rgb' \
        -o /data/output/entwine/cesium \
        -c /data/scripts/entwine/convert/config.json 

Entwine: Converting Entwine Point Cloud to Cesium 3D Tiles...
Encountered an error: Invalid argument: -c
Exiting.
```

Note: I can pass in a config file without issue for `build`.

Lastly, while I have you, can you explain the significance of `scale` in the config for `build`? When I run `scan` on my las model, the scale is determined to be `0.1`. I am not sure if that has some affect on the density or general quality of the output image.

Thanks for your help.

**Comment by connormanning** [comment]
Fixed the argument handling.  Geometric error should be the only thing you'd need to tweak for your case - I believe you can also scale it within Cesium rather than re-converting an Entwine dataset but I'm not positive about this.  Note that Entwine's `geometricErrorDivisor` is a scale factor - the root PNTS file will have a geometric error of `octreeCubeWidth / geometricErrorDivisor`, which will halve at each subsequent octree depth.  This allows nearby datasets of varying bounding sizes but equal `geometricErrorDivisor` values to be loaded at similar resolutions.

Regarding scale - this will have no effect on Cesium since Entwine's Cesium conversion uses floating values for XYZ.  For LAS/LAZ, this is simply the precision of the data at which values may be truncated such precision is not lost.

**Comment by devdylan** [comment]
Awesome, thanks for the prompt reply. I pulled the latest docker image and verified that `convert` can accept `--geometricErrorDivisor`.
