### ISSUE TITLE
user migration to ept

### ISSUE THREAD

**Issue by wakruse** [connormanning/entwine#119]
I'm testing the migration to the new ept data format and workflow(s) using docker running on aws ec2 and have several questions. I realize that the ept tool chain isn't released yet and so some functionality may be missing. It is also possible that I have overlooked something in the evolving documentation currently available online.

- Viewing indexed ept point clouds with Potree in a remote browser works fine using an http server reading the ept data from the local file system on an aws ec2 instance. Is there an http(s) server application that uses arbiter or equivalent to support secure reading by pottree of the ept data from s3 instead of the ec2 local file system like greyhound did before. Is there a better approach.

- Is accessing ept indexed data using PDAL's reader.greyhound now supported by the greyhound :ept docker file or by another method?

- When entwine (entwine:ept, entwine:latest) is indexing thousands of tiles, input from s3 and output to s3, it slows down significantly after several hundred tiles and continues to consume memory. I'm using 16 threads on 16 cores with 122GB of memory. Entwine build options include "--resetfiles 100 -p. By 4000 tiles memory usage grows to the maximum. Using  --run 1000 or --subset x y reduces the memory an performance bottleneck but still starting at with cpu usage at ~75% and ending up with ~30%.  It appears that the network traffic between ec2 and s3 is not a bottleneck. All builds completed successfully.

Thanks in advance for any best practices suggestions you can provide.

**Comment by connormanning** [comment]
- Since S3 has an option to serve bucket statically over HTTP, that is the recommended method.  In fact that's how the back-end data for [potree.entwine.io](http://potree.entwine.io) and [speck.ly](http://speck.ly) are served.
- No, there will be a readers.ept for this, but it doesn't exist yet.
- You could try tweaking the thread counts [doc](https://github.com/connormanning/entwine/blob/master/doc/configuration.md#threads).  It may be that entwine's performance characteristics aren't quite right for your specific datasets.  Subsetting, as you've mentioned, may also be useful in this case.

**Comment by connormanning** [comment]
There's now a `readers.ept` in PDAL master, which will be in the next PDAL release.  Docs are [here](https://github.com/PDAL/PDAL/blob/master/doc/stages/readers.ept.rst) in the meantime.
