### ISSUE TITLE
Cartesian reprojection

### ISSUE THREAD

**Issue by Need4Speed402** [connormanning/entwine#180]
I am working with massive data sets the size of provinces such as Ontario and we are trying to display this lidar on top of a standard ortho-imagery base map. However we are running into issues where in the lidar that potree is rendering is not matching up with the base layer that is correctly rendered. I suspect that when Potree is trying to display the lidar it is making the assumption that the coordinate system is of a cartesian system however everything is projected to a system similar to WGS based off of easing, northing and elevation which is relative to the curvature of the earth. Because of the non linear nature of WGS, Potree has troubling rending Lidar in the correct position especially points further from the camera. At least that is what my stipulation is. To fix the issue I was thinking that I would need to reproject the coordinate system to some kind of non standard system based on a cartesian coordinate system before running Entwine so that the data will display in the proper position relative to my basemap.

I'm not asking that you help me add a feature to Entwine to do this reprojection, all I am asking is if my theory is plausible so that I can start working on a tool that could reproject this stuff before the Entwine stage. Apparently Entwine is also quite stingy about the coordinate system so I am worried that if I do make this reprojection tool entwine would reject anything that it produces. I want to make sure that putting effort into this is not a waste of time.

If you want to get some visual confirmation of this, you can take a look at [this terrible clip I whipped up](https://youtu.be/1Eyui6I3bnY). All I can tell you is that it looks weird especially when I tilt the camera upwards.

**Comment by connormanning** [comment]
I've seen similar behavior when the vertical datum of point cloud data does not match that of the underlying layer - resulting in strange shifting/collapsing as you rotate the view.  And if your imagery is overlaid onto the WGS84 ellipsoid with Ontario having an elevation of ~300m, your clip could make sense.  For example, it looks similar to this [clip](https://entwine.io/data/ellipsoid-to-terrain.mov) I've made to demonstrate.

> all I am asking is if my theory is plausible

I don't know, reprojecting into a "non standard system" doesn't sound like something you should need to do.  And if you do need cartesian, why would it need to be non-standard instead of simply ECEF?  Regardless, you should be able to test your theory quite easily by testing your reprojections on small patches near the extents of your datasets.  Leading to the next item:

> Entwine is also quite stingy about the coordinate system

This part is interesting.  How does this manifest?  Entwine simply passes reprojections down to PDAL (via the reprojection filter) which defers to GDAL which defers to Proj.  This is pretty much the "how to reproject" workflow of every geo project in existence, so I'm surprised you find it deficient.  If there's an error or limitation in entwine's usage, this would be worthy of its own ticket if you could provide details.  You could also reproject your data prior to using entwine, which would allow you to validate your theory independent of entwine's reprojection capabilities.

You might consider asking Markus in the potree repo about the rendering aspect of this ticket.

**Comment by Need4Speed402** [comment]
Hello again, thanks a lot for the help. I was not familiar with the ECEF projection and that is basically exactly what I want. Regarding testing the theory, I have confirmed it by generating two las files.[Archive.zip](https://github.com/connormanning/entwine/files/3122738/Archive.zip) contains two las files, one projected with EPSG:4978 and the other with EPSG:4326 and contains points representing the prime meridian and equator. The cartesian las file rendered with potree is displayed correctly as a global view with the points wrapping around the world. The other however renders as a flat surface, not accurate with the curvature of the earth. The 4326 projection completely fails to render correctly on any kind of base map on many apps that I have tried. I was correct in thinking that the non-linear nature of the 4326 projection caused the parallax nature. The datum of a dataset dictates the severity of the problem but choosing a datum that is closest to the source data is still not a complete fix especially for bigger datasets that deviate more from the datum.

Regarding the comment about Entwine being stingy with the coordinate system, I was simply proxying a comment from my co-worker who is responsible for transforming this data, he had concerns that Entwine did not take some projections saying something about in not being in the database. Don't worry about that, I personally did not have issues with Entwine. Works flawless as long as you have enough allocated memory.
