### ISSUE TITLE
Problem with dimension size

### ISSUE THREAD

**Issue by nicolas-chaulet** [connormanning/entwine#183]
In some cases (large scaling factor in a las input) the data type for X,Y and Z should be `uint64` but they are fixed to `uint32`. A possible solution is to use the `absolute` parameter but then it seems that `laz` for output becomes broken (misses scale) and setting the `scale` property does not help. So, the work around is to serialise to `bin` and set `absolute` to `true` but I guess we could do something better and let `scan` decide if it needs 32 or 64 bits. I tried to implement that but broke other tests. I also see that the code base has massively evolved since the last commit to master. So maybe it's been fixed now... The following tests could be used:

```
TEST(build,scaleProblem)
{
    const std::string outPath(test::dataPath() + "out/bbox/");
    const std::string metaPath(outPath + "ept-sources/");

    // Pass
    Config c(json {
        { "input", test::dataPath() + "broken-box.las" },
        { "output", outPath },
        {"absolute", true},
        {"dataType", "binary"},
        { "force", true },
        { "span", v.span() },
        { "hierarchyStep", v.hierarchyStep() }
    });

    // Fails
    c = Config(json {
        { "input", test::dataPath() + "broken-box.las" },
        { "output", outPath },
        { "force", true },
        { "span", v.span() },
        { "hierarchyStep", v.hierarchyStep() }
    });
    Builder(c).go();
}
```

Link to the test file:
https://drive.google.com/file/d/1joaeW4d2hmrGfvaCPK0a0Cwpo_LbtdP2/view?usp=sharing

**Comment by connormanning** [comment]
The LAS format does not allow 64-bit XYZ - they must be 32-bit scaled integers.  See [spec](https://www.asprs.org/wp-content/uploads/2010/12/LAS_1_4_r13.pdf) (Ctrl+F for `point data record format 0` and onward from there).

I think we should simply throw an error on initialization if `laz` is selected but the data extents are too large for 32-bit XYZ values.  That would go [here](https://github.com/connormanning/entwine/blob/master/entwine/types/metadata.cpp#L84), where we are checking that the data fits within the selected scale/offset/XYZ-width, but we are not currently checking that the XYZ-width is appropriate for the output format.

> I also see that the code base has massively evolved since the last commit to master

Expect a PR soon with discussion of this.

**Comment by nicolas-chaulet** [comment]
> The LAS format does not allow 64-bit XYZ - they must be 32-bit scaled integers. See [spec](https://www.asprs.org/wp-content/uploads/2010/12/LAS_1_4_r13.pdf) (Ctrl+F for `point data record format 0` and onward from there).

So technically speaking my file is not correct (exported from CloudCompare). It still goes through Pdal nicely though. So I am wondering if we could have a similar way to handle this case that still allows indexing to happen? We could for example set the scale so that it fits within the extent and log a warning?

**Comment by connormanning** [comment]
Your data itself is fine, and has 32-bit XYZ values or else it wouldn't be a LAS file.  The problem is that your data has its XYZ scales set such that they fill nearly the entire 32-bit space.  CloudCompare probably generates these absurd values to avoid potentially losing precision from your data, if I were to guess.  So when Entwine bloats the box out a bit and creates its bounding cube but retains the original scale, it exceeds the maximal extents.  This is a duplicate of #113, really.

The fix, as you say, is to simply set the scale to something more reasonable.  Currently, the onus to do this is on the user since it's potentially lossy.  However for your data, the current scaling is arbitrary and doesn't represent anything real (unless your data *is* actually precise to nanometer scale 😉).

I've been wary of doing this automatically for a few reasons:
1) it's possible we could eliminate precision that *is* real, but this is pretty rare and could be solved just by logging a warning.  Most people hitting this error have arbitrarily scaled data.
2) it's very preferable that users set a scale that is actually meaningful because the scale is a vessel for precision information.  Your data is advertising its precision to nanometer resolution, so the proper solution is that you set a scale that's accurate to the precision of your input source.
3) compression performs poorly with such high precision, which would be fine if the data were actually that precise, but here the output will larger for no reason.

I'm not sure of a good solution here.  Maybe simply improving the error message to say something like:
```Set the scale factor with --scale to a minimum of 0.0000001 to proceed.```

**Comment by nicolas-chaulet** [comment]
Yes makes sense. The thing that puzzled me was that Pdal was just fine with it but now I understand why. The error message you suggest would definitely help! Closing that one now, thanks for taking a look!
