### ISSUE TITLE
batchTable Support on entwine 2.0 ?

### ISSUE THREAD

**Issue by obendidi** [connormanning/entwine#187]
Hi @connormanning,

Thanks for this great tool, any idea on when `batchTable` will be supported in entwine 2.0 ? 

according to what you said [here](https://github.com/connormanning/entwine/issues/118#issuecomment-407607536) , it's probably easy to port, and I'll be happy to make a PR if you show me the way 

I've been using entwine 1.3.0-maintenance for my conversions to cesium, but it doesn't work as well when used in an ubuntu docker (RAM exploding to more than 240 Gb 😱 on 100 Gb folder of Lidar data, hangs in some other cases or throws and `std_logic` error  ...) while I had no problem with the official 1.3 docker image on alpine.

I'm using 1.3 only for the support of `batchTable` so if it could be ported to 2.0, it will be a better solution than trying to fix the 1.3 version I think

Thanks

**Comment by connormanning** [comment]
This is quite low on the roadmap and will likely rely on community contribution.  It's unfortunate that the existing contribution, which was much appreciated, was developed at such a time when breaking changes for 2.0 were already well in progress.  Here is some information which would be useful for someone trying to implement this port:

It was originally implemented in #85, and most of the functionality lives in the `batch-reference` and `batch-table` cpp/hpp files [here](https://github.com/connormanning/entwine/tree/1.3.0-maintenance/entwine/formats/cesium).  Some things have changed since then.

Notably, Entwine now uses a different [JSON library](https://github.com/nlohmann/json) which is used quite a bit throughout the 3D Tiles metadata code.  The 3D Tiles directory in Entwine has also been simplified quite a bit (compare [1.3](https://github.com/connormanning/entwine/tree/1.3.0-maintenance/entwine/formats/cesium) with [master](https://github.com/connormanning/entwine/tree/master/entwine/formats/cesium)) and should be much easier to conceptualize.

Unit tests (perhaps using the [3D Tiles validator](https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/tree/master/validator)) or an update to the very outdated [entwine-cesium-pages](https://github.com/connormanning/entwine-cesium-pages) demo repository, including a small sample dataset with a batch table, would be very helpful in making sure that the 3D Tiles code continues to stay up to date.

Happy to answer any questions encountered along the way (and perhaps the original batch table implementer @andrensairr would chime in as well).
