### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by tomvantilburg** [connormanning/entwine#22]
On latest github version.
Building with pdal 1.3, with lazperf.

```
[ 91%] Building CXX object test/CMakeFiles/entwine-test.dir/unit/build.cpp.o
/var/data/git_repos/entwine/test/unit/build.cpp:38:9: error: ‘PointId’ is not a member of ‘{anonymous}::D {aka pdal::Dimension::Id}’
         D::PointId, D::OriginId
         ^

```

[entwine_error.txt](https://github.com/connormanning/entwine/files/649468/entwine_error.txt)

**Comment by connormanning** [comment]
Since PDAL will soon have a new release which will be Entwine's requirement, currently Entwine needs the latest version of PDAL.  Soon after the PDAL 1.4 release, Entwine will have a 1.0 release - so things will be more stable at that point.  Because of some breaking API changes in PDAL, Entwine has no compatibility with 1.3.

For now, please use a current PDAL build (I've also updated Entwine, just now, for a new change from the PDAL API, so you'll have to re-pull Entwine as well).  Sorry for the instability at the moment.

**Comment by tomvantilburg** [comment]
I should have tried that myself. Works now. :)
