### ISSUE TITLE
Invalid root path

### ISSUE THREAD

**Issue by opaulsen** [connormanning/entwine#229]
I'm install entwine with anaconda3 in windows
`conda create -n entwine -c conda-forge entwine`

then i go to the path of my pointcloud and run:
`(entwine) C:\>entwine build -i odm_georeferenced_model.laz -o entwine_pointcloud/`
and i receive this error:
`Scanning input`
`1/1: odm_georeferenced_model.laz`
`Exception in pool task: During odm_georeferenced_model.laz: Invalid root path`
`SRS could not be determined`
`Encountered an error: No points found!`
`Exiting.`

i can build the test with:
`entwine build -i https://data.entwine.io/red-rocks.laz -o red_rocks/`

also prove with the full path and installing like #226:
`conda create -n entwine -c conda-forge entwine pdal=2.0.1`

**Comment by connormanning** [comment]
Yes, this is a very unhelpful error message.  This is due a bug in the Conda release that you are using (it is fixed in the current code and will work properly in Conda after a new release which is coming in the next few weeks).  To work around it, you need to add `./` in front of your local paths, so try: `entwine build -i ./odm_georeferenced_model.laz -o entwine_pointcloud/`
