### ISSUE TITLE
Discrepancy of offset in ept.json vs LAZ metadata

### ISSUE THREAD

**Issue by wonder-sk** [connormanning/entwine#245]
I am seeing different values reported for "offset" of Y dimension in ept.json compared to what is then stored in .laz files of the octree (e.g. the root node 0-0-0-0.laz).

- in 0-0-0-0.laz metadata: `-1204300`
- in ept.json: `-1204303`

If the client's parser trusts offsets from ept.json, this causes unwanted shift of 3 meters.

Offsets of other dimensions seem to match in my particular test data (15 MB):
https://drive.google.com/file/d/1Zs3cLikFX2UWIbk5fIrlc4NhWN_zll2D/view?usp=sharing

**Comment by connormanning** [comment]
The root cause of this issue is pdal/pdal#3235.  Entwine sets these offsets [here](https://github.com/connormanning/entwine/blob/master/entwine/io/laszip.cpp#L68-L70), and in this particular case, PDAL transits the value `-1204303` through the string `-1.2043e+06`, chopping off the last digit.  Unsure of what action Entwine can/should take at this time, but I'll leave this open until it's resolved.

**Comment by connormanning** [comment]
This has been addressed upstream in PDAL.
