### ISSUE TITLE
Status of Cesium 3D Tiles conversion

### ISSUE THREAD

**Issue by alarsyo** [connormanning/entwine#248]
Hi, thanks for all the work that went into Entwine!

Does it still support conversion from EPT to Cesium 3D Tiles format? [The documentation](https://entwine.io/configuration.html#convert) mentions the `convert` command but the `master` branch doesn't seem to contain any code that handles this argument.

Is this functionality no longer supported?

**Comment by connormanning** [comment]
Correct, this is no longer supported by Entwine software directly, but instead via a separate project called [ept-tools](connormanning/ept-tools).

**Comment by tfiner** [comment]
First, thank you for entwine and I am liking the nice tools developed by you and @hobu (esp. PDAL).

Question: why?  Is there some kind of documentation / blog post on why the switch to JS and the subsequent dropping of convert functionality from entwine?  This bug report is the only mention I could find of this change. The online documentation for convert is still up too, so that confused me until I found this issue report.  Are there problems with the output from entwine's convert?  I'd like to use it, but with knowledge of where the issues lie.

Comment: Node.js is definitely a step backwards from an operational point of view and entwine's convert appears to work well in my tests.  Ept-tools, like everything else I've seen that depends on node, is a PITA to get going.  For example: I tried installing ept-tools and could not get it to install.  One of the dependencies required a newer node.js than the one supplied with a modern version of Ubuntu (20.04).  After a few more problems of this nature, I uninstalled ept tools (only to find that it didn't truly uninstall), then uninstalled node.

I ended up cloning this repo and rewound it to just before the convert code got yanked and compiled entwine.  I compiled it for Win32 because the performance was much faster than running through WSL / Ubuntu and am able to generate 3d tiles with it.

**Comment by connormanning** [comment]
I've never heard anyone say before that a C++ application is easier to get up and running than a NodeJS one :)

But seriously @tfiner, Entwine's `convert` was very limited.
- No batch table support, so Classification/Intensity (which had to be hard-mapped to RGB to see it)/Elevation/ReturnNumber/all the other good stuff were not supported
- Data was required to be in EPSG:4978 which tends to be undesirable for any purpose *aside* from conversion to 3D Tiles

And just in general, the model of duplicating data is a pain.  EPT as an intermediate step to some other format is not what we want.  The whole point of EPT Tools is that without duplicating your data, you can live translate to 3D Tiles as needed (although the on-disk conversion is still supported) - the EPT format itself is hopefully designed to be useful enough that you can use it for all your point cloud needs - visualization with Potree/Cesium/QGIS, processing with PDAL, etc.

And with that context, where the converter is running as a live server or in something like AWS Lambda, NodeJS is an obvious choice.  Doing the translation live allows for some interesting options, like allowing an intelligent Cesium client to request dynamically only the attributes that are needed, for example this occurs in http://autzen.entwine.io.  Or exposing the entire [USGS EPT datasets](https://usgs.entwine.io) as 3D Tiles on the fly without needing to double the existing 20+TB into 40+TB of another format.  Hopefully some of this reasoning makes sense, even if you disagree with the change in workflow.

All that said, if `entwine convert` is working for your use-case, I think your method of simply using an old Entwine release which supported it is perfectly fine.  But I'd still encourage you to look a little harder into making the new workflow work.  [Option 2 here](https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-20-04) should work just fine for installing a recent NodeJS version on Ubuntu.  Or if you have Docker available, you can get up and running as easily as `docker pull node; docker run -it node bash; npm install -g ept-tools; ept --help;`.

**Comment by tfiner** [comment]
Fair enough: I'll bet I'm in the minority on C++ being easier to get set up!  ;)

Thanks for all the information and I think your reasoning makes a lot of sense.  I will give ept-tools another shot.

**Comment by hobu** [comment]
> Question: why? Is there some kind of documentation / blog post on why the switch to JS and the subsequent dropping of convert functionality from entwine?

Our needs have changed, and there hasn't been any funding to support the old `convert` approach. As always, money can protect pet features from being removed and unmaintained in future releases 😄

**Comment by tfiner** [comment]
I totally understand.
