### ISSUE TITLE
how subset works ?

### ISSUE THREAD

**Issue by julienlau** [connormanning/entwine#274]
I found this in the doc :

> Entwine builds may be split into multiple subset tasks, and then be merged later with the merge command. Subset builds must contain exactly the same configuration aside from this subset field.
> 
> Subsets are specified with a 1-based id for the task ID and an of key for the total number of tasks. The total number of tasks must be a power of 4.

However, I don't understand if the subsetting needs the full input datasets and produce only a subset of the output dataset.
Or, if by specifying correctly the BBOX of all datasets, I can do subsetting without having all input files ?

**Comment by connormanning** [comment]
You can perform an `info` to a serialized output, and then use that predetermined metadata as the input to subset `build` commands.  In that case, theoretically you could supply each subset with only its needed files, and even though you would use the same `info` output which contains *all* files, only the relevant ones for each subset would be needed.

However, figuring out which files are needed is *not* done by Entwine and you would need to write your own application to do that via the `bounds` of each input.  In general this is not an explicitly supported workflow, since subsets are typically used in 2 cases:
- the data is remote e.g. in S3
- you are trying to do several small/fast builds rather than one big one iteratively (for example running 16 subsets on your laptop to use less memory than just one big build)

In both of these cases, you have all of the data readily available to each subset so this is a non-issue.  To do something more specialized, you would have to write some code for your specific use-case.
