### ISSUE TITLE
Entwine contains a copy-paste of GoogleTest (with mismatching license)

### ISSUE THREAD

**Issue by defaultbranch** [connormanning/entwine#284]
**Current**

The Entwine code contains copy-paste content from GoogleTest. This is problematic for at least two reasons:

- the GoogleTest code comes with its own license, which is different from the Entwine license
- this copy-pasting instead of referencing breaks any simple tracking/checking/upgrading

**Expected**

The Entwine code should be only Entwine code, without needing copy-paste content; and following/tracking/upgrading external dependencies should be simple (make issues such as #233 easier)

---

I will try to post a PR to solve this.

**Comment by hobu** [comment]
The GoogleTest code is [vendored](https://codeengineered.com/blog/2015/go-should-i-vendor/) because gtest is not commonly available on all platforms Entwine runs on, and it is the GoogleTest community's common dependency practice with the library. We are not going to be merging a PR that makes gtest an external dependency. If you made a PR that updated the vendored version to 1.12.1 and fixed and resulting issues from that effort, we would be happy to merge.
