### ISSUE TITLE
Question: Cesium 3D Tiles output

### ISSUE THREAD

**Issue by pierotofy** [connormanning/entwine#29]
I'm currently trying to produce a Cesium 3D Tiles output using the following:

```
docker run -it --rm -v /mylasfiles:/mylasfiles -v $HOME:$HOME connormanning/entwine build /var/entwine/config/cesium.json -i "/mylasfiles/job295165_46092_68_05.laz" -o ~/entwine/output
```

Am I correct in assuming that I cannot (and don't need to) use Greyhound to serve the ~/entwine/output folder? A simple static node.js/python http server should do, right?

By running Greyhound I can access a URL such as: `http://localhost:8080/resource/superior/info`, but I can't find an URL mapping for the Cesium path (I looked through the code and I think this is correct, but wanted to confirm).

Thanks!

**Comment by connormanning** [comment]
The Cesium configuration actually produces two builds - a standard Entwine index (which you can serve with Greyhound) and a Cesium 3D-Tiles tileset in the output's `cesium` directory.

So, with your Greyhound server running locally you should be able to use http://speck.ly?s=localhost:8080&r=superior or http://potree.entwine.io/data/custom.html?s="localhost:8080"&r="superior" to view the standard Entwine index served by Greyhound.

For the 3D-Tiles tileset, you are correct that that is not meant to be served from Greyhound.  For this, you would create a `Cesium.Viewer` using the cesium.js library and add your statically served tileset URL as a scene primitive.  There's a pre-built set of static pages at https://github.com/connormanning/entwine-cesium-pages where you can test this out if you don't have a Cesium environment set up already.

**Comment by pierotofy** [comment]
That's what I thought. Would there be any interest in adding a route to serve the static contents of the cesium directory into Greyhound, so that a user wanting to serve both type of builds could do so without running two servers?

I could make a PR for it.

Thanks for the explanation!

**Comment by connormanning** [comment]
I'm not sure I'd recommend that, with the current state of Entwine's Cesium-build support, since Entwine's functionality is limited when the Cesium config is specified.  For example, continued/subset builds are not supported, scale/offset is not supported (although this one is trivial to add), and there are also some issues related to how the transformation stuff works to output to ECEF that can make the Entwine index for a Cesium build less efficient.  So if you are targeting Greyhound, it's better not to use the Cesium configuration.

Another thing that would need to be considered is that Greyhound supports S3/HTTP/Dropbox/etc. back-ends, and those details are hidden from clients.  So if resource `a` lived on the local filesystem, then it could be statically accessed, but resource `b` on S3 could not, with no way to advertise that fact in advance without an API change.

A longer-term goal for Greyhound is to generate 3D-Tiles output dynamically from a standard Entwine index, but that's not going to happen right away.  I think at this point I'd recommend keeping Greyhound/Cesium separate, even though Entwine can target both.

**Comment by pierotofy** [comment]
Makes sense, thanks again!
