### ISSUE TITLE
Question:  Point streaming not supported for stage readers.ply

### ISSUE THREAD

**Issue by jfinken** [connormanning/entwine#37]
I am unable to index a point cloud in binary PLY.  More specifically, running:
```
DATA=/path/to/ply/
docker run -it -v $DATA:/opt/data connormanning/entwine build \
  -i /opt/data/my.ply \
  -o /opt/data/entwine
```

I get:
```
Performing dataset inference...
1 / 1: /opt/data/my.ply
Exception in pool task: Point streaming not supported for stage readers.ply.
Cannot use this scale for these bounds
Encountered an error: Zero points found
Exiting.
```

A similar result from `infer`:

````
docker run -it -v $DATA:/opt/data connormanning/entwine infer /opt/data/my.ply
Inferring from: /opt/data/my.ply
	Temp path: tmp
	Threads: 4
	Reprojection: (none)
	Trust file headers? yes
1 / 1: /opt/data/my.ply
Exception in pool task: Point streaming not supported for stage readers.ply.
Cannot use this scale for these bounds
Encountered an error: Zero points found
Exiting.
````
Expected?  Thank you in advance.

**Comment by connormanning** [comment]
Yes - this is expected for PDAL readers that don't support streaming.  Most of them do have support for streaming, and there's no reason it can't be added for `ply`.  However, Entwine should also have a fallback to the non-streaming PDAL API from within Entwine to avoid this error for other readers in the future.

**Comment by connormanning** [comment]
In the meantime you could convert to something like BPF to allow you to index your data, e.g. `pdal translate f.ply f.bpf`.

**Comment by jfinken** [comment]
_Many_ thanks for the rapid response.  

I confess I am still reading up on the PDAL API etc but can you help define _streaming_ in this context?  From what I can tell from the docs on [Stage::execute()](https://www.pdal.io/api/cpp/stage.html#_CPPv2N4pdal5Stage7executeER16StreamPointTable) _streaming_ is effectively defined as reading a small number of points from disk into a table in memory, processing that table, then repeat until EOF.

And thank you for the suggestion to first convert to BPF, I'll give that a go.  
Regards.

**Comment by connormanning** [comment]
A stage (i.e. reader, writer, or filter) supports *streaming* if it implements [processOne](https://github.com/PDAL/PDAL/blob/master/pdal/Stage.hpp#L432).

The default method of operation for PDAL is that all points are read into memory before being anything else happens.  This is because many filters need random access into all points in their dataset to operate.

However, because this isn't always necessary, there's a second mode of operation which operates on a fixed number of points at a time.  When all required stages are streamable, this avoids the overhead of allocating all the points at once.  Most of them implement streaming mode already, but that hasn't yet been done for PLY.

Entwine currently uses this method of the API exclusively, which causes the problem you've seen for readers that aren't streamable.  A fallback to the other method would be nice in this case.
