### ISSUE TITLE
Creating big 3d-tiles

### ISSUE THREAD

**Issue by aleksandrmelnyk** [connormanning/entwine#44]
Hi,

Is it possible to proceed creating 3d tiles index for cesium if previoosly command was interrupted (say due to SSH)? If source data is pretty big (hundreds of gb) generating tiles would take long, so ability to continue previous job would be very useful.

thanks,

Alex.

**Comment by adamsteer** [comment]
Hi Alex,

I usually use screen (google 'man screen') to prevent long running jobs from being killed by ssh dropouts. This is pretty much 'set fly and forget', you need to check in to find out whether jobs get killed or not. Another option is nohup, eg:

# nohup entwine build....

**Comment by aleksandrmelnyk** [comment]
Adam thanks,

gonna try that.

**Comment by connormanning** [comment]
Adam's suggestions are also what I'd recommend.  I'll also add that if you are using docker, then you can run with the `-d` flag instead of `-it`, which will detach the session and leave it running in the background.  For example:

`docker run -d --name entwine connormanning/entwine build ...`

Then to attach to the log output:
`docker logs entwine -f`

**Comment by aleksandrmelnyk** [comment]
With cesium format we didn't succeed to build any larger data set. Last command failed silently (meaning that entwine didn;t get enough memory within docker), in cesium.json "threads": 2
`docker run --memory=16g --memory-swap=2g --kernel-memory=24g -v /data:/data connormanning/entwine build  /data/entwine/options/cesium.json`
That dataset consists of many laz files 50-200 MB each, total 16GB.

**Comment by adamsteer** [comment]
Hey @aleksandrmelnyk - what is your host machinery? OS/specs? I reckon this might be a docker/machine config issue rather than entwine - I recently built a 700+tile/26bill point dataset, it consumed about38GB RAM (out of 48GB available) and ran for about 30 hours. I’ve previously built a 7.4 billion point dataset using a 16GB/4cpu virtual machine, which required thread limiting (-t 2) to work, but it chugged away and did it. I needed to give it about 8Gb of swap if I recall correctly.

I will look at the docs and see if I can add anything helpful about this stuff.

@connormanning - what are your thoughts on setting up an entwine gitter channel for this type of discussion? A good issue/feature request for here might be ‘entwine consumes a lot of RAM, can it consume less? and how?’ - whereas general help topics/chitchat/advice (mea culpa also) might be better discussed elsewhere. Also @aleksandrmelnyk what do you think?

Should I raise an issue to ‘create entwine community channel?’ Currently the entwine community page leads to the PDAL list.

**Comment by aleksandrmelnyk** [comment]
Hi @adamsteer, we have 32GB at total, 8 core CPU, ubuntu 16.04. When we allocate like 30GB for docker system just kills whole process (code 137). 
Did you succeeded to build for cesium format or for potree/greyhound one?

**Comment by aleksandrmelnyk** [comment]
Seems like with cesium format entwine RAM usage continuously grows till the process is killed by system or container.

**Comment by aleksandrmelnyk** [comment]
>A good issue/feature request for here might be ‘entwine consumes a lot of RAM, can it consume less
think its quite good idea

**Comment by adamsteer** [comment]
HI @aleksandrmelnyk , my experience is that creating 3d tiles consumes more than a plain entwine build - but definitely reaches a limit and stays there. Let me capture some observations over the next few days, with some larger data than yours. I feel that manually controlling docker memory may be an issue, but don’t *know*.  Also, have you pulled the latest entwine build? `entwine —version` should return 1.1.0 - @connormanning worked on cesium tile build memory issues ahead of that release.

**Comment by connormanning** [comment]
For a more efficient Cesium workflow, see #98.  Please open a new ticket for any issues with that.
