### ISSUE TITLE
Cesium3D tile creation: scaling problem

### ISSUE THREAD

**Issue by kbeamnsidc** [connormanning/entwine#74]
I am running entwine build on a las file which I've created by extracting points from a pgpointcloud table. I'm attempting to create Cesium3D tiles. 

The extraction and creation of the input las file is done by a simple PDAL pipeline, the writer of which is configured like this:
```
        {
            "type":"writers.las",
            "filename":"jakobshavn1993.las",
            "scale_x": "0.000020",
            "scale_y": "0.000020",
            "scale_z": "0.01"
        }
```
However, when I run entwine build on the output, I get errors like the following: 

```Exception in pool task: writers.las: Unable to convert scaled value (-3680219298) to int32 for dimension 'X' when writing LAS/LAZ file /home/kbeam/jakobshavn1993/19607957362005.laz.```

Is the exception due to the reprojected X value, not the original unprojected X value? If I understand correctly, the Cesium3D tiles are reprojected to EPSG:4978. Is there a way to avoid this scaling / data size problem?

**Comment by connormanning** [comment]
The error is based on the reprojected value.  You'll need to back off the scale factor a bit - `0.00002` is quite aggressive.  I'd try setting `-s 0.001` to see if that gets things building.

**Comment by kbeamnsidc** [comment]
I confirm that it does work if I increase the scale factor. But I'm still a little puzzled why this is necessary. Here's a little more info:

- I have just over 7e6 points in a pgpointcloud table.
- I extract them via a pdal pipeline into a LAS file. 
[lasinfo output](https://github.com/connormanning/entwine/files/1616627/lasinfo.txt)

- Then I run `entwine build` on the LAS file which has output that I'll also attach. 
[entwine build output](https://github.com/connormanning/entwine/files/1616628/entwine.txt)


From the lasinfo the source data has bounds:

```
  Min X, Y, Z: 		-52.107223, 66.684020, 11.91
  Max X, Y, Z: 		-35.960430, 72.236515, 3249.52
  Bounding Box:		-52.107223, 66.684020, -35.960430, 72.236515
```

So the source data is in lat/lon (epsg 4326) and has resolution down to 1e-6. It seems that this should be scalable to fit in an int32, even after reprojected, but I probably don't understand the target projection range. Can you give me any pointers based on this info on whether this scaling problem is expected or if there is something I should investigate about my data?

**Comment by adamsteer** [comment]
hey @kbeamnsidc - `Unable to convert scaled value (-3680219298) to int32 ` occurs because it’s unsigned value is larger than the largest possible int32 number (https://en.wikipedia.org/wiki/2,147,483,647)

Your entwine output says the same: `unable to convert scaled value (5.598515272e+10) to int32` - again `5.59..e+10` can’t fit into int32.

So winding back scaling helps, since you then have smaller numbers to write to int32. Adding an offset also helps - although may not be effective with data in dd.ddd. Working in metres, adding an offset to your LAZ files effectively resets stored int values to local coordinates, so they work unless your survey is extremely large (yours appears to be pretty big!! - curious - ICEBRIDGE?)

f you’re working on Greenland, be careful also that degrees of latitude need to scale a bit differently to degrees of longitude - `0.00002 * (degree lat) = 2.239m`;`0.0002 * (degree lon) = 0.8 m`, and longitude will be a bit different at the southern bound of your survey than at the northern bound.

HTH

**Comment by kbeamnsidc** [comment]
Yes, it is IceBridge!
I'm closing this as I think this input has been helpful. Thanks everyone!
