### ISSUE TITLE
Entwine file format specification

### ISSUE THREAD

**Issue by martinheidegger** [connormanning/entwine#78]
I was reading through the source code of entwine and while It would be possible to figure out the index format that entwine creates somehow I failed to find a comprehensive documentation, so as a feature request or issue: Would it be possible to add information about presentations, papers or specifications regarding the data storage of entwine to the repository?

**Comment by hobu** [comment]
@connormanning talked a bit about the format at FOSS4G 2016. You can see the video of his talk [here](https://av.tib.eu/media/20366). 

We also have been working on a paper to more thoroughly describe things, but it is not yet complete. https://entwine.io/configuration.html#tree-depths talks a little bit about tree organization, but mostly from the perspective of a user/consumer.

I'll note that we use [Greyhound](https://greyhound.io) to provide abstract access to Entwine resources, and it is likely your best source of "how to get what I need out of an Entwine data structure" at the moment. 

We've been talking about developing a Web Mercator-only Potree-like static format based off of Entwine's data structure, but we have not yet implemented it. If you are digging into Entwine's implementation details because you want something like that, it might be better to collaborate with us on that specific topic rather than digging into the entrails of Entwine.

**Comment by hobu** [comment]
@connormanning's talk from 2017 goes into detail about how Greyhound works which might be helpful too. https://vimeo.com/245073446

**Comment by martinheidegger** [comment]
Thank you for the references, I am reading through them now. 

>We've been talking about developing a Web Mercator-only Potree-like static format based off of Entwine's data structure, but we have not yet implemented it.

That sounds awesome.

> If you are digging into Entwine's implementation details because you want something like that, it might be better to collaborate with us on that specific topic rather than digging into the entrails of Entwine.

I would love to join/collaborate with you but before I would like to understand the progress you have made thus far and understand all the tricks you used for entwine _(don't want to bore you with noob-talk)_.

**Comment by connormanning** [comment]
See #98.
